x-default-opts: &default-opts
  logging:
    options:
      max-size: "1m"

services:
  music-assistant-server:
    <<: *default-opts
    image: ghcr.io/music-assistant/server:${MA_TAG}
    volumes:
      - music_assistant_data:/data/
    networks:
      - macvlan_swarm # Connect to the same network as Home Assistant
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    security_opt:
      - apparmor:unconfined
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  macvlan_swarm:
    external: true

volumes:
  music_assistant_data:
    driver: local
    driver_opts:
      device: ${HOST_MUSIC_ASSISTANT_DATA} # Bind mount to host path from .env
      type: none
      o: bind