x-default-opts: &default-opts
  env_file:
    .env
  logging:
    options:
      max-size: "1m"

services:
  calrs:
    <<: *default-opts
    image: ghcr.io/olivierlambert/calrs:${CALRS_TAG}
    volumes:
      - data:/var/lib/calrs
    environment:
      CALRS_BASE_URL: ${CALRS_BASE_URL}
    networks:
      - proxy_network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        traefik.enable: "true"
        traefik.http.routers.calrs.entrypoints: ${ENTRYPOINT:-websecure}
        traefik.http.routers.calrs.rule: Host(`${DOMAIN:-calrs.host.local}`)
        traefik.http.routers.calrs.service: calrs
        traefik.http.services.calrs.loadbalancer.server.port: 3000

  backup:
    <<: *default-opts
    image: alpine:latest
    volumes:
      - data:/var/lib/calrs
      - backup:/backup
    command:
      - sh
      - -c
      - |
        apk add --no-cache sqlite;
        echo "[$$(date +'%Y-%m-%d %H:%M:%S')] Backup service started. First backup will be executed in $$BACKUP_FREQUENCY.";
        while true; do
          backup_file=/backup/calrs_backup_$$(date +%Y%m%d_%H%M%S).sqlite.gz;
          echo "[$$(date +'%Y-%m-%d %H:%M:%S')] Creating backup of CalRS SQLite database...";
          sqlite3 /var/lib/calrs/data.db .dump | gzip > $$backup_file;
          find /backup -name 'calrs_backup_*.sqlite.gz' -mtime +$$RETENTION_DAYS -delete;
          echo "[$$(date +'%Y-%m-%d %H:%M:%S')] Backup completed. Next backup in $$BACKUP_FREQUENCY.";
          sleep $$BACKUP_FREQUENCY;
        done
    deploy:
      restart_policy:
        condition: on-failure
        delay: 600s

networks:
  proxy_network:
    external: true

volumes:
  data:
    driver: local
    driver_opts:
      device: ${HOST_CALRS_DATA}
      type: none
      o: bind

  backup:
    driver: local
    driver_opts:
      device: ${HOST_CALRS_BACKUP}
      type: none
      o: bind
