x-default-opts: &default-opts
  logging:
    options:
      max-size: "1m"

services:
  immich-server:
    <<: *default-opts
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - immich_upload_data:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    environment:
      DB_PASSWORD_FILE: /run/secrets/immich_db_password
    secrets:
      - source: immich_db_password
        target: immich_db_password
    env_file:
      - .env
    networks:
      - immich_network
      - proxy_network
    healthcheck:
      disable: false
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        traefik.enable: "true"
        traefik.http.routers.immich.entrypoints: ${ENTRYPOINT:-websecure}
        traefik.http.routers.immich.rule: Host(`${DOMAIN:-immich.host.local}`)
        traefik.http.routers.immich.service: immich-server
        traefik.http.services.immich-server.loadbalancer.server.port: 2283

  immich-machine-learning:
    <<: *default-opts
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    networks:
      - immich_network
    healthcheck:
      disable: false
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  redis:
    <<: *default-opts
    image: docker.io/redis:6.2-alpine@sha256:148bb5411c184abd288d9aaed139c98123eeb8824c5d3fce03cf721db58066d8
    healthcheck:
      test: redis-cli ping || exit 1
    networks:
      - immich_network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  database:
    <<: *default-opts
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/immich_db_password
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_DB: ${DB_DATABASE_NAME:-immich}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # Uncomment if database is on HDD (not SSD): DB_STORAGE_TYPE: 'HDD'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    secrets:
      - source: immich_db_password
        target: immich_db_password
    shm_size: 128mb
    networks:
      - immich_network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

secrets:
  immich_db_password:
    external: true

networks:
  immich_network:
    driver: overlay
    attachable: true
  proxy_network:
    external: true

volumes:
  immich_upload_data:
    driver: local
    driver_opts:
      device: ${HOST_IMMICH_UPLOAD_DATA} # Bind mount to host path from .env
      type: none
      o: bind
  postgres_data:
    driver: local
    driver_opts:
      device: ${HOST_POSTGRES_DATA} # Bind mount to host path from .env
      type: none
      o: bind
  model-cache: 
    driver: local
    driver_opts:
      device: ${HOST_CACHE_DATA} # re-use cache_data path from .env for model-cache
      type: none
      o: bind