version: '3.9'

x-default-opts: &default-opts
  env_file:
    .env
  logging:
    options:
      max-size: "1m"

services:
  ha:
    <<: *default-opts
    container_name: homeassistant
    image: homeassistant/home-assistant:${HA_TAG}
    volumes:
      - ha_config:/config
      - /etc/localtime:/etc/localtime:ro
      - /dev/serial/by-id:/dev/serial/by-id
      - /run/dbus:/run/dbus:ro
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    ports:
      - 8123:8123
    network_mode: host
    restart: always
      
volumes:
  ha_config:
    driver: local
    driver_opts:
      device: ${HOST_HA_DATA}
      type: none
      o: bind