version: '3.9'

x-default-opts: &default-opts
  env_file:
    .env
  logging:
    options:
      max-size: "1m"

services:
  zigbee2mqtt:
    <<: *default-opts
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:${Z2M_TAG}
    volumes:
      - z2m_data:/app/data
      - /run/udev:/run/udev:ro
    networks:
      - mqtt
    ports:
      - 8080:8080
    devices:
      # Make sure this matched your adapter location
      - /dev/ttyUSB0:/dev/ttyACM0
    restart: always

networks:
  mqtt:
    external: true
    name: mqtt_network
      
volumes:
  z2m_data:
    driver: local
    driver_opts:
      device: ${HOST_Z2M_DATA}
      type: none
      o: bind