version: '3.8'

x-default-opts: &default-opts
  logging:
    options:
      max-size: "1m"
    # driver: "gelf"
    # options:
    #   gelf-address: "udp://172.17.0.1:12201"

services:
  image-prune:
    <<: *default-opts
    image: docker
    command: sh -c "while true; do docker image prune -af --filter \"until=240h\"; sleep 86400; done"
    networks:
      - bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

  container-prune:
    <<: *default-opts
    image: docker
    command: sh -c "while true; do docker container prune -f --filter \"until=24h\"; sleep 86400; done"
    networks:
      - bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

  volume-prune:
    <<: *default-opts
    image: docker
    command: sh -c "while true; do docker volume rm $$(docker volume ls -qf dangling=true); sleep 86400; done"
    networks:
      - bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

networks:
  bridge:
    external: true
    name: bridge