version: '3.9'

x-default-opts: &default-opts
  env_file:
    .env
  logging:
    options:
      max-size: "1m"

services:
  ha:
    <<: *default-opts
    image: homeassistant/home-assistant:${HA_TAG}
    volumes:
      - ha_config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    networks:
      - proxy_network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
      labels:
        traefik.enable: "true"
        traefik.http.routers.homeassistant.entrypoints: ${HA_ENTRYPOINT:-websecure}
        traefik.http.routers.homeassistant.rule: Host(`${HA_DOMAIN:-hass.host.local}`)
        traefik.http.routers.homeassistant.service: homeassistant
        traefik.http.services.homeassistant.loadbalancer.server.port: 8123

networks:
  proxy_network:
    external: true
      
volumes:
  ha_config:
    driver: local
    driver_opts:
      device: ${HOST_HA_DATA}
      type: none
      o: bind