version: '3.8'

x-default-opts: &default-opts
  env_file:
    .env
  logging:
    options:
      max-size: "1m"
    # driver: "gelf"
    # options:
    #   gelf-address: "udp://172.17.0.1:12201"

services:
  web:
    <<: *default-opts
    image: wordpress:${WORDPRESS_TAG}
    networks:
      - proxy_network
      - wp_network
    volumes:
      - data:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_NAME=${DB_NAME}
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        traefik.enable: "true"
        traefik.http.routers.wordpress.entrypoints: ${ENTRYPOINT:-websecure}
        traefik.http.routers.wordpress.rule: Host(`${DOMAIN?Variable not set}`)
        traefik.http.routers.wordpress.service: wordpress
        traefik.http.services.wordpress.loadbalancer.server.port: 80

  db:
    <<: *default-opts
    image: mariadb:${MARIADB_TAG}
    networks:
      - wp_network
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  backup:
    <<: *default-opts
    image: mariadb:${MARIADB_TAG}
    command: 
      - sh
      - -c
      - | 
        echo "[$$(date +'%Y-%m-%d %H:%M:%S')] Backup service started. First backup will be executed in $$BACKUP_FREQUENCY.";
        while true; do
          sleep $$BACKUP_FREQUENCY;
          backup_dir=/backup/wordpress_$$(date +'%Y%m%d_%H%M%S');
          mkdir -p $$backup_dir;
          echo "[$$(date +'%Y-%m-%d %H:%M:%S')] Creating backup of WordPress data including SQL dump of $$DB_NAME database...";
          /usr/bin/mysqldump -u $$DB_USER --password=$$DB_PASSWORD --host=db --databases $$DB_NAME --no-tablespaces > $$backup_dir/db.sql;
          tar -C /data/ -cvzf $$backup_dir/data.tar.gz .;
          find /backup/wordpress_* -mtime +$$RETENTION_DAYS -exec rm -rf {} \;
          echo "[$$(date +'%Y-%m-%d %H:%M:%S')] Backup completed. Next backup in $$BACKUP_FREQUENCY.";
        done
    volumes:
      - backup:/backup
      - data:/data
    networks:
      - wp_network
    deploy:
      restart_policy:
        condition: on-failure
        delay: 600s

networks:
  proxy_network:
    external: true
    
  wp_network:
    driver: overlay

volumes:
  data:
    driver: local
    driver_opts:
      device: ${HOST_WORDPRESS_DATA}
      type: none
      o: bind
      # device: ":${HOST_WORDPRESS_DATA?Variable not set}"
      # type: nfs
      # o: addr=${NFS_SHARE_IP?Variable not set},rw,sync,nfsvers=4.1

  db:
    driver: local
    driver_opts:
      device: ${HOST_WORDPRESS_DB}
      type: none
      o: bind
      # device: ":${HOST_WORDPRESS_DB?Variable not set}"
      # type: nfs
      # o: addr=${NFS_SHARE_IP?Variable not set},rw,sync,nfsvers=4.1

  backup:
    driver: local
    driver_opts:
      device: ${HOST_WORDPRESS_BACKUP}
      type: none
      o: bind
      # device: ":${HOST_WORDPRESS_BACKUP?Variable not set}"
      # type: nfs
      # o: addr=${NFS_SHARE_IP?Variable not set},rw,sync,nfsvers=4.1